### ISSUE TITLE
Morph2 dataset website is dead

### ISSUE THREAD

**Issue by noelcodes** [shamangary/SSR-Net#11]
Morph2 dataset website is dead. Do you happen to have the dataset for download?

**Comment by shamangary** [comment]
Sorry, I cannot provide the dataset due to the morph2 dataset requires an application and some payment.
I have no idea why the dataset website is down. You have to ask the authors of the dataset.

**Comment by noelcodes** [comment]
Since morph db is dead, therefore i am trying to modify run_ssrnet.sh. I noticed u have nested for looped imdb + wiki with i,j.  I am confused, because your demo is only taking either wiki OR imdb weights. I planned to cut down train time by not looping, but not sure if this mess up the model concept. 

So I want to clarify, your purpose of the for-loop, is it because you are taking the last train weights from imdb for start weights for wiki, then continued loop using last wiki weight for start imdb and so on and on...?  

I was planning to train only this: but not sure.
python SSRNET_train.py --input ../data/imdb_db.npz --db imdb --netType1 1 --netType2 1

**Comment by shamangary** [comment]
No. The for loop is just for different hyper parameters. Different model from different hyper parameters do not take each others pretrained weight.

**Comment by noelcodes** [comment]
Any idea why?
It throw me an error when I run training without loop, just this cmd> 
python SSRNET_train.py --input ../data/imdb_db.npz --db imdb --netType1 1 --netType2 1
Error: 
UnicodeDecodeError: 'rawunicodeescape' codec can't decode bytes in position 838-839: truncated \uXXXX


====================================================================================================
Total params: 40,915
Trainable params: 40,531
Non-trainable params: 384
____________________________________________________________________________________________________
DEBUG:root:Saving model...
Traceback (most recent call last):
  File "SSRNET_train.py", line 136, in <module>
    main()
  File "SSRNET_train.py", line 95, in main
    f.write(model.to_json())
  File "C:\Users\default.LAPTOP-2CI68M4P\Anaconda3\envs\xrvision2\lib\site-packages\keras\engine\topology.py", line 2618, in to_json
    model_config = self._updated_config()
  File "C:\Users\default.LAPTOP-2CI68M4P\Anaconda3\envs\xrvision2\lib\site-packages\keras\engine\topology.py", line 2585, in _updated_config
    config = self.get_config()
  File "C:\Users\default.LAPTOP-2CI68M4P\Anaconda3\envs\xrvision2\lib\site-packages\keras\engine\topology.py", line 2322, in get_config
    layer_config = layer.get_config()
  File "C:\Users\default.LAPTOP-2CI68M4P\Anaconda3\envs\xrvision2\lib\site-packages\keras\layers\core.py", line 656, in get_config
    function = func_dump(self.function)
  File "C:\Users\default.LAPTOP-2CI68M4P\Anaconda3\envs\xrvision2\lib\site-packages\keras\utils\generic_utils.py", line 175, in func_dump
    code = marshal.dumps(func.__code__).decode('raw_unicode_escape')
UnicodeDecodeError: 'rawunicodeescape' codec can't decode bytes in position 838-839: truncated \uXXXX
